[package]
name = "auxmos"
version = "0.1.0"
authors = ["Putnam <putnam3145@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
monstermos = []
explosive_decompression = ["monstermos"]

[lib]
crate-type = ["cdylib"]

[dependencies]
auxtools = { git = "https://github.com/willox/auxtools" }
auxcallback = { git = "https://github.com/Putnam3145/auxcallback" }
lazy_static = "1.4.0"
itertools = "0.9.0"
smallvec = "1.4.2"
rayon = "1.5.0"
float-ord = "0.2.0"
crossbeam = "0.8.0"
flume = "0.9.1"
coarsetime = "0.1.16"
parking_lot = "0.11.1"

[dependencies.dashmap]
version = "3.11.10"
features = ["raw-api"]

[profile.release]
debug = true
